### ISSUE TITLE
Improving /artistalbums & /artisttracks in YouTube Music version of server (Not sure if this will even be used in future, as it is not used in the Harmonoid right now).

### ISSUE THREAD

**Issue by alexmercerind** [raitonoberu/harmonoid-service#8]
Now the accuracy of the server is even better than the things like [spotify-downloader](https://github.com/ritiek/spotify-downloader). Congratulations.

This is probably first of a kind app to download music from YouTube Music (not YouTube). You should consider rebranding the repository & project. 
P.S : How about making a CLI version?

**Comment by alexmercerind** [comment]
Greetings @raitonoberu 🥳 !

The updated server with YouTube Music is now deployed at https://harmonoid.herokuapp.com/.
I don't know what to expect from this server at the moment.

Other changes made by me:
- Pushed YouTube Music version of the server to "master" with mandatory fixes & changes (and deployed to https://harmonoid.herokuapp.com/ for testing).
- Made separate permanent branch for old Spotify Server with name "spotify".
- Deleted "_develop" branch.
- "vnext" is now obsolete, now please commit changes against the "master" branch for YouTube version of the server & in "spotify" for the Spotify version of the server (I don't think we will ever need that). You can delete "vnext" once you are done reviewing.
- Closed #7 as [ytmusicapi](https://github.com/sigma67/ytmusicapi) is now successfully working for the most part & opened #8 for some long-term fixes to /artistalbums & /artisttracks

Thank you & have a great day! 😊

**Comment by alexmercerind** [comment]
And @mytja! 
First of all, greetings.
You can try out the new YouTube Music based server.

Thank you 😃

**Comment by raitonoberu** [comment]
Hello @alexmercerind!
I'm finally home😁. All the commits you made today are great! Searching is working as expected.

But downloading the track doesn't work, and I know why. `TrackInfo` method requires `albumId` parameter, but I don't think that it's necessary. If album ID is not specified, we should probably search for it. I will fix it soon.

Thanks a lot :)

**Comment by alexmercerind** [comment]
Thanks a lot!

My main priority was to fix /albuminfo & include the missing keys in the result (which I fixed).
Performance is still close to same (as I'm making network requests parallelly).

Ah yes! I didn't think that I can make albumId optional. But from now on, Harmonoid will be sending artist_id as a query parameter for better downloads.
As expected, downloads are 100% accurate now.

And, feel free to improve stuff (I'm not the most efficient programmer 😅).

**Comment by raitonoberu** [comment]
> You should consider rebranding the repository & project.

Done. In my opinion, the original name (**harmonoid-service**) is best.

**Comment by alexmercerind** [comment]
Now I feel it's time to start fixing these features as we're going to add an artists search.

**Comment by raitonoberu** [comment]
Ok, dat works. You can test it here:
http://harmonoid-ru.herokuapp.com/artistalbums?artist_id=UCwZEU0wAwIyZb4x5G_KJp2w
http://harmonoid-ru.herokuapp.com/artisttracks?artist_id=UCwZEU0wAwIyZb4x5G_KJp2w

**Comment by alexmercerind** [comment]
Excellent 😃!

(You rickrolled me btw 😏😂.)

Should this issue be closed now?

**Comment by raitonoberu** [comment]
Yeah :)
